version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/webapp
  - source: express.service
    destination: /etc/systemd/system
hooks:
  AfterInstall:
    - location: scripts/after_install.sh
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 15
  ValidateService:
    - location: scripts/validation.sh